
        GBLS    fcerror
fcerror SETS    "FileCoreErr"

        MACRO
$num    FileCoreErr $name, $str
        LCLS    line
line    SETS    "#define $name.Err "
        WHILE   :LEN: line < 32
line    SETS    line :CC: " "
        WEND
        =       line, "(0x$num)", 10
        MEND


        GET     ListOpts
        GET     FSNumbers

        AREA    Text, DATA

        ; File header
        =       "/* This is an autogenerated file, do not edit */", 10, 10
        =       "#ifndef INTERFACE_FILECOREERR_H_", 10
        =       "#define INTERFACE_FILECOREERR_H_", 10, 10

        ; Define all the errors that FileCore generates for the FS
        GET     hdr/FileCoreErr

        ; File footer
        =       10, "#endif", 10

        ; Pad to word alignment with newline characters
        ALIGN   4, 0, 10


        END
