#!/bin/bash
make -j$(getconf _NPROCESSORS_ONLN) sdl comma2attr HardDisc4/stamp

mv 'HardDisc4/!Boot/Choices/Boot/Tasks/Pinboard'* 'HardDisc4/!Boot/Choices/Boot/Tasks/Pinboard,feb' 2> /dev/null
touch 'HardDisc4/!Boot/Choices/Boot/Tasks/Pinboard,feb'
sort -u > Pinboard 'HardDisc4/!Boot/Choices/Boot/Tasks/Pinboard,feb' - << END
X AddTinyDir IXFS::Root.\$.dev.fd.4
X AddTinyDir IXFS::Root.\$
X AddTinyDir IXFS::Root.\$$(echo $HOME | tr ./ /.)
X AddTinyDir IXFS::Root.\$.dev.fd.8
END
setfattr -n user.RISC_OS.LoadExec -v 0x00ebffff00000000 Pinboard
mv Pinboard 'HardDisc4/!Boot/Choices/Boot/Tasks/Pinboard,feb'

RISC_OS_Alias_IXFSBoot='/IXFS:$.dev.fd.4.!Boot' exec ./sdl ./run ./RISC_OS --nvram HardDisc4/CMOS 4<HardDisc4 8<. > /dev/null
