/* Copyright 1996 Acorn Computers Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef steppable_H
#define steppable_H

/*steppable_s.h - support for a slider with adjust arrows and a writable
icon*/

/*From OSLib*/
#ifndef os_H
   #include "os.h"
#endif

#ifndef wimp_H
   #include "wimp.h"
#endif

/*From Support*/
#ifndef callback_H
   #include "callback.h"
#endif

#ifndef task_H
   #include "task.h"
#endif

typedef struct steppable_s *steppable_s;

 /* Types for the callbacks generated by this module.
  */
typedef os_error *steppable_value_changed (steppable_s v, int value,
      osbool dragging, void *);

typedef os_error *steppable_caret_moved (steppable_s, wimp_w, wimp_i,
      void *);

typedef
   struct steppable_steppable
   {  task_r r;
      callback_l list;
      wimp_w w;
      int value;
      int min; int max; int div;
      /*the slider*/
      wimp_i knob; wimp_i track;
      /*adjusters*/
      wimp_i up; wimp_i down;
      /*writable*/
      wimp_i writable; int prec;
      steppable_value_changed *value_changed_fn;
      steppable_caret_moved *caret_moved_fn;
      void *handle;
   }
   steppable_steppable;

 /* Function to register all the callbacks needed by the given steppable_s,
  * and map them to calls to the given callback functions. Also sets the
  * steppable_s to the given initial value.
  */

extern os_error *steppable_register (steppable_steppable *, steppable_s *);

 /* Function to deregister the callbacks and dispose of the steppable_s.
  */

extern os_error *steppable_deregister (steppable_s v);

 /* Function to set a steppable_s to a value, updating the icons
  * appropriately.
  */

extern os_error *steppable_set_value (steppable_s v, int value);

 /* Function to get the value of a steppable_s.
  */

extern os_error *steppable_get_value (steppable_s v, int *value);

#endif
