/* This source code in this file is licensed to You by Castle Technology
 * Limited ("Castle") and its licensors on contractual terms and conditions
 * ("Licence") which entitle you freely to modify and/or to distribute this
 * source code subject to Your compliance with the terms of the Licence.
 * 
 * This source code has been made available to You without any warranties
 * whatsoever. Consequently, Your use, modification and distribution of this
 * source code is entirely at Your own risk and neither Castle, its licensors
 * nor any other person who has contributed to this source code shall be
 * liable to You for any loss or damage which You may suffer as a result of
 * Your use, modification or distribution of this source code.
 * 
 * Full details of Your rights and obligations are set out in the Licence.
 * You should have received a copy of the Licence with this source code file.
 * If You have not received a copy, the text of the Licence is available
 * online at www.castle-technology.co.uk/riscosbaselicence.htm
 */
/* c.genjhdr - simple program to make suitable assembler header
files from certain C structure defintions, to make sharing of those
structures between C and assembler a little bit easier. */

#include <stdio.h>
#include <stddef.h>

#include "jpeglib.h"

int main(void)
{
  printf("; s.jhdr, generated by genjhdr %s %s.\n\n", __DATE__, __TIME__);

  /* Defined constants */
  printf("DCTSIZE * %i\n", DCTSIZE);
  printf("DCTSIZE2 * %i\n", DCTSIZE2);
  printf("\n");

  /* Exposed bits of jpeg_decompress_struct */
  printf("cinfo_jpeg_buffer * %i\n", offsetof(struct jpeg_decompress_struct, jpeg_buffer));
  printf("cinfo_jpeg_buffer_size * %i\n", offsetof(struct jpeg_decompress_struct, jpeg_buffer_size));
  printf("cinfo_workspace_size * %i\n", offsetof(struct jpeg_decompress_struct, workspace_size));
  printf("\n");

  printf("\n        END\n\n");

  return 0;
}
