stages:
  - static_analysis

certdata:
  stage: static_analysis
  tags: [ cross ]
  script:
    - "# Checking CertData..."
    - test $(stat -c%s Resources/files/CertData) -gt 1000
    - test $(grep -- "-----BEGIN CERTIFICATE-----" Resources/files/CertData | wc -l) -gt 50
    - "# CertData looks good"
