
        GBLS    FSName
FSName  SETS    "SCSIFS"

        GBLS    fcerror
fcerror SETS    "FSErr"

        MACRO
$num    FSErr   $name, $str
        =       "        AddError $FSName.$name, ""$str"", &"
        =       :STR: (&10000 + fsnumber_$FSName:SHL:8 + &$num), 10
        MEND


        GET     ListOpts
        GET     FSNumbers

        AREA    Text, DATA

        ; File header
        =       "; This is an autogenerated file, do not edit", 10, 10

        ; Define all the errors that FileCore generates for the FS
        GET     FileCoreErr

        ; Define additional FS errors
72      FSErr   SectorSizeNotSupported, Sector size not supported
76      FSErr   BadSCSIType, Bad SCSI device type

        ; File footer
        =       10, "        END", 10

        ; Pad to word alignment with newline characters
        ALIGN   4, 0, 10


        END
