/* This source code in this file is licensed to You by Castle Technology
 * Limited ("Castle") and its licensors on contractual terms and conditions
 * ("Licence") which entitle you freely to modify and/or to distribute this
 * source code subject to Your compliance with the terms of the Licence.
 * 
 * This source code has been made available to You without any warranties
 * whatsoever. Consequently, Your use, modification and distribution of this
 * source code is entirely at Your own risk and neither Castle, its licensors
 * nor any other person who has contributed to this source code shall be
 * liable to You for any loss or damage which You may suffer as a result of
 * Your use, modification or distribution of this source code.
 * 
 * Full details of Your rights and obligations are set out in the Licence.
 * You should have received a copy of the Licence with this source code file.
 * If You have not received a copy, the text of the Licence is available
 * online at www.castle-technology.co.uk/riscosbaselicence.htm
 */
/*> h.DOSFS <*/
/*-------------------------------------------------------------------------*/
/* System static variables                      Copyright (c) 1990 JGSmith */
/*-------------------------------------------------------------------------*/

#ifndef __h_DOSFS
#define __h_DOSFS

/*-------------------------------------------------------------------------*/

typedef unsigned char   byte ;
typedef unsigned int    word ;

#define MAX(a,b)        ((a)>(b)?(a):(b))
#define MIN(a,b)        ((a)<(b)?(a):(b))
#define WORDALIGN(v)    (((v) + 3) & ~3)
#define UNUSED(x)       ((x) = (x))    /* deal with unused parameters */
#ifndef FALSE
#define FALSE           0
#define TRUE            (!FALSE)
#endif

/*-------------------------------------------------------------------------*/
/* global (static) variables used within the module */
extern void *dosfs_msgarea(void); /* Generated by 'resgen' */
extern int discopswi;
extern int module_flags ;         /* Global flags, mixture of: */
#define TRUNCATE_NAMES        0x00000001

#include "DOSshape.h"

/* The DOSMAP structure */
typedef struct mapentry {
                         struct mapentry *next ;
                         char             dosext[8] ; /* 7 chars + NULL */
                         word             ROtype ; /* lo 12bits */
                        } mapentry ;

extern mapentry *maplist ;      /* list of defined mappings */

/*-------------------------------------------------------------------------*/
/* Data return structures to RISC OS world (from C module world) */

extern FS_open_block fblock ;
extern FS_datestamp  tstamp ;
extern FS_cat_entry  fcat ;
extern FS_dir_block  dblock ;
extern FS_free_space fspace ;

/*-------------------------------------------------------------------------*/
/* open file handle list */

extern FILEhand *FILE_list ;

/*-------------------------------------------------------------------------*/
/* DOS disc type descriptions */

typedef struct DOSdiscinfo {
/* format identifier      */ char *idtext;
/* format table entry     */ byte findex;
/* show in format menu?   */ byte in_menu;
/* The following used for constructing boot block: */
/* shape identity byte    */ byte magic_ID;
/* secs/cluster           */ byte secsclus;
/* secs/FAT               */ byte secsFAT;
/* root directory size    */ byte rootsize;
                           } DOSdiscinfo;

/*-------------------------------------------------------------------------*/

#endif /* __h_DOSFS */

/*-------------------------------------------------------------------------*/
/*> EOF h.DOSFS <*/
