
        GBLS    FSName
FSName  SETS    "adfs"

        GBLS    fcerror
fcerror SETS    "FSErr"

        MACRO
$num    FSErr   $name, $str
        =       "        AddError $FSName.$name, ""$str"", &"
        =       :STR: (&10000 + fsnumber_$FSName:SHL:8 + &$num), 10
        MEND


        GET     ListOpts
        GET     FSNumbers

        AREA    Text, DATA

        ; File header
        =       "; This is an autogenerated file, do not edit", 10, 10

        ; Define all the errors that FileCore generates for the FS
        GET     FileCoreErr

        ; Define additional FS errors
11      FSErr   FormatEsc, Escape whilst formatting (disc structure invalid)
70      FSErr   FormatNotSupportedOnWinnie, Format not available for Winnies
71      FSErr   DensityNotSupported, Density not supported
72      FSErr   SectorSizeNotSupported, Sector size not supported
73      FSErr   TooManySectors, Too many sectors on a track
74      FSErr   BadFormat, Bad format
75      FSErr   TooManyDefects2, Too many defects
76      FSErr   NoFloppy, Floppy drive not connected
A0      FSErr   DriverInUse, Driver in use

        ; File footer
        =       10, "        END", 10

        ; Pad to word alignment with newline characters
        ALIGN   4, 0, 10


        END
