/* This source code in this file is licensed to You by Castle Technology
 * Limited ("Castle") and its licensors on contractual terms and conditions
 * ("Licence") which entitle you freely to modify and/or to distribute this
 * source code subject to Your compliance with the terms of the Licence.
 * 
 * This source code has been made available to You without any warranties
 * whatsoever. Consequently, Your use, modification and distribution of this
 * source code is entirely at Your own risk and neither Castle, its licensors
 * nor any other person who has contributed to this source code shall be
 * liable to You for any loss or damage which You may suffer as a result of
 * Your use, modification or distribution of this source code.
 * 
 * Full details of Your rights and obligations are set out in the Licence.
 * You should have received a copy of the Licence with this source code file.
 * If You have not received a copy, the text of the Licence is available
 * online at www.castle-technology.co.uk/riscosbaselicence.htm
 */
/*
 * Matrix1
 *
 * Copyright (C) Pace Micro Technology plc. 2001
 *
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>

static void write_file(FILE *f, char *argv[])
{
  time_t t;
  int x;

  time(&t);
  fprintf(f, "; > %s\n;\n; Generated by %s at %s;\n", argv[1], argv[0], ctime(&t));
  fputs("LookupTable", f);

  for (x=0; x<128; ++x) {
    int y = 0;

    y += ((x >> 0) & 1) * 1;
    y += ((x >> 1) & 1) * 2;
    y += ((x >> 2) & 1) * 3;
    y += ((x >> 3) & 1) * 4;
    y += ((x >> 4) & 1) * 3;
    y += ((x >> 5) & 1) * 2;
    y += ((x >> 6) & 1) * 1;

    if (!(x & 15)) fputs("\n        DCB     ", f); else fputc(',', f);
    fprintf(f, "&%02X", y);
  }

  fputs("\n\n        END\n\n", f);
}

int main(int argc, char *argv[])
{
  FILE *f;

  if (argc != 2) {
    fprintf(stderr, "Syntax: %s <output file>\n", argv[0]);
    exit(EXIT_FAILURE);
  }

  f = fopen(argv[1], "w");
  if (!f) {
    fprintf(stderr, "%s: unable to open %s for output\n", argv[0], argv[1]);
    exit(EXIT_FAILURE);
  }

  write_file(f, argv);
  fclose(f);

  return EXIT_SUCCESS;
}
